language: python
python:
  - 3.8

addons:
  artifacts:
    paths:
      - files

install:
  - python -m pip install --upgrade pip
  - pip3 install -r requirements.txt
  - python3 -m sphinx -b html . _build/html
