image: python:3-alpine

generating docs:
  script:
  - python -m pip install --upgrade pip
  - pip3 install -r requirements.txt
  - cd files/maletero
  - apk --no-cache add make
  - python3 -m sphinx -b html . _build/html
  - mv _build/html/ ../
  artifacts:
    paths:
    - files
  only:
  - master
